Azure-Samples/iot-edge-opc-plc

docker/windows/amd64/Dockerfile
Update Windows container to use 1809 as base image.
=> updated windows docker file to use 1809 as base

GitVersion.yml, opcplc/AssemblyInfo.cs, opcplc/Program.cs, opcplc/opcplc.csproj
=> add gitversion support

opcplc/OpcApplicationConfiguration.cs, opcplc/Program.cs
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Added command line option to control authentication modes

README.md
@hansgschossmann - To complete onboarding to the Azure samples experience, please set up the Webhook and grant write access to the service account as described here: https://review.docs.microsoft.com/en-us/help/onboard/admin/samples/process/onboarding?branch=master
=> Onboard to Azure samples

tools/templates/acrbuild.yml
Fix build pipeline variable handling.
=> Fix build pipeline variable handling

.editorconfig, .gitignore, README.md, opcplc.sln, src/PlcNodeManager.cs, src/PlcServer.cs, src/PlcSimulation.cs, src/Program.cs, src/Properties/launchSettings.json, src/Startup.cs, src/opc-plc.csproj
Make pn.json filename configurable to allow local sharing with other containers.
Other minor changes and doc updates.
=> Make pn.json filename configurable, other minor changes

README.md
=> Fix link to ARM template

src/PlcNodeManager.cs, src/PlcSimulation.cs
* Change all child values in one transactional step
=> Update complex type in one atomic step

src/Boiler/BoilerModel.NodeSet2.xml, src/Boiler/BuildDesign.bat, src/PlcNodeManager.cs, src/PlcSimulation.cs
* Also use supported model version 1.04
=> Fix start without param

src/PlcNodeManager.cs, src/PlcSimulation.cs, src/Program.cs, src/SimulatedNode.cs, src/SimulatedVariableNode.cs
* Add node with long ID (3950 chars)
* Refactor to make it easier to add more nodes with special characteristics
=> Add node with long id

README.md, src/OpcApplicationConfiguration.cs, src/PlcNodeManager.cs, src/PlcSimulation.cs, src/Program.cs, src/SimulatedVariableNode.cs, tools/templates/azuredeploy.opcplc.aci.json, version.json
* 10/50 kB string
* 100 kB ByteString
* 200 kB ByteArray
* The strings change every second and represent one random uppercase letter concatenated to fill the respective node
=> Add nodes with long strings

src/OpcApplicationConfigurationSecurity.cs, src/Program.cs
=> Fix help command

src/Program.cs
Be able to see if Boiler simulation is enabled/disabled
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
* Start with parameter --ctb and see in logging info it is enabled
* Start without paramter --ctb and se in logging info that it is disabled
```
cd [repo-name]
npm install
```
```
```
* ...
=> feat: added logging message to see if Boiler feature is enabled/disabled

src/SimpleEvent/SimpleEventsNodeManager.cs, src/opc-plc.csproj
A bug fix for wrong path to predefined uanode file to simpleevent
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix wrong path to predefined uanode file for simpleevents

src/SimpleEvent/SimpleEventsNodeManager.cs, src/opc-plc.csproj
Update Namespace for SimpleEvetn
```
[ ] Yes
[x] No
```
```
[x ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Fix wrong namespace for simpleevent

README.md, src/Namespaces.cs, src/PlcServer.cs, src/PlcSimulation.cs, src/Program.cs, src/Reference/ReferenceNodeManager.cs, version.json
* add lots of nodes of all datatypes, arrays, methods, etc for testing purposes #47 
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> add reference test node manager

src/OpcApplicationConfigurationSecurity.cs, src/opc-plc.csproj
Cherry picked from https://github.com/Azure-Samples/iot-edge-opc-plc/tree/mregen/nuget
Closing #44
=> Update to latest OPC UA nuget and fix private key issue

src/PlcSimulation.cs
* Fix the behavior of the AlternatingBoolean node. Probably this was misconfigured because of a copy-paste glitch.
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
Run with UAExpert
* AlternateBoolean node value is toggled every 5 seconds
=> Fix behavior of AlternateBoolean node

src/Nodes/DeterministicGuidNodes.cs, src/Nodes/INodes.cs, src/Nodes/LongIdNodes.cs, src/Nodes/LongStringNodes.cs, src/Nodes/SpecialCharNameNodes.cs, src/PlcNodeManager.cs, src/PlcSimulation.cs, src/Program.cs
* Encapsulate small features to clean-up PlcNodeManager
* SpecialCharNameNodes, LongIdNodes and LongStringNodes
=> Encapsulate small features

src/Nodes/DeterministicGuidNodes.cs, src/Nodes/INodes.cs, src/Nodes/LongIdNodes.cs, src/Nodes/LongStringNodes.cs, src/Nodes/SpecialCharNameNodes.cs, src/PlcNodeManager.cs, src/PlcSimulation.cs, src/Program.cs
* Automate adding nodes that implement INode (to make them like plugins)
* Including printing Publisher config, adding to address space, starting and stopping simulation
=> Automate adding INodes

src/PlcNodeManager.cs, src/PluginNodes/DataPluginNodes.cs, src/PluginNodes/DeterministicGuidPluginNodes.cs, src/PluginNodes/DipPluginNode.cs, src/PluginNodes/IPluginNodes.cs, src/PluginNodes/LongIdPluginNode.cs, src/PluginNodes/LongStringPluginNodes.cs, src/PluginNodes/NegTrendPluginNode.cs, src/PluginNodes/PosTrendPluginNode.cs, src/PluginNodes/SpecialCharNamePluginNode.cs, src/PluginNodes/SpikePluginNode.cs, src/PluginNodes/UserDefinedPluginNodes.cs, src/Program.cs
* Check if a folder exists before creating it to avoid duplicate issue
* Move small feature nodes to "Special Nodes" folder
* Other small refactoring
=> Move small feature nodes to "Special Nodes" folder

README.md, src/PlcNodeManager.cs, src/PlcServer.cs, src/PlcSimulation.cs, src/PluginNodes/DataPluginNodes.cs, src/PluginNodes/DeterministicGuidPluginNodes.cs, src/PluginNodes/DipPluginNode.cs, src/PluginNodes/FastPluginNodes.cs, src/PluginNodes/IPluginNodes.cs, src/PluginNodes/LongIdPluginNode.cs, src/PluginNodes/LongStringPluginNodes.cs, src/PluginNodes/Models/IPluginNodes.cs, src/PluginNodes/Models/NodeWithIntervals.cs, src/PluginNodes/NegTrendPluginNode.cs, src/PluginNodes/NodeWithIntervals.cs, src/PluginNodes/PosTrendPluginNode.cs, src/PluginNodes/SlowFastCommon.cs, src/PluginNodes/SlowPluginNodes.cs, src/PluginNodes/SpecialCharNamePluginNode.cs, src/PluginNodes/SpikePluginNode.cs, src/PluginNodes/UserDefinedPluginNodes.cs, src/Program.cs, src/opc-plc.csproj, tests/GuidNodesTests.cs, tests/PlcSimulatorFixture.cs, tests/SimulatorNodesTests.cs, tests/SimulatorTestsBase.cs, tests/opc-plc-tests.csproj
* Encapsulate slow and fast nodes as plugins
* Move iPlugin models to subfolder
* Update nuget packages
* Fix tests
=> Encapsulate slow and fast nodes

src/CliOptions.cs, src/PlcNodeManager.cs, src/PlcSimulation.cs, src/PluginNodes/ComplexTypeBoilerPluginNode.cs, src/PluginNodes/DataPluginNodes.cs, src/PluginNodes/FastPluginNodes.cs, src/PluginNodes/NegTrendPluginNode.cs, src/PluginNodes/PosTrendPluginNode.cs, src/PluginNodes/SlowPluginNodes.cs, src/Program.cs
* Encapsulate feature as plugin for better separation of concerns
* Refactor slow/fast nodes method wiring for consistency
=> Encapsulate complex type boiler

src/PlcNodeManager.cs, src/PlcSimulation.cs
* Mode simulation code from node manager to plc simulation
=> Refactor event simulation code

src/OpcApplicationConfiguration.cs
* Add security policy Basic256Sha356 - Sign
Closes #66
=> Add MessageSecurityMode.Sign

src/Helpers/PnJsonHelper.cs, src/Namespaces.cs, src/PluginNodes/ComplexTypeBoilerPluginNode.cs, src/PluginNodes/DataPluginNodes.cs, src/PluginNodes/DeterministicGuidPluginNodes.cs, src/PluginNodes/DipPluginNode.cs, src/PluginNodes/FastPluginNodes.cs, src/PluginNodes/LongIdPluginNode.cs, src/PluginNodes/LongStringPluginNodes.cs, src/PluginNodes/Models/NodeWithIntervals.cs, src/PluginNodes/NegTrendPluginNode.cs, src/PluginNodes/PosTrendPluginNode.cs, src/PluginNodes/SlowPluginNodes.cs, src/PluginNodes/SpecialCharNamePluginNode.cs, src/PluginNodes/SpikePluginNode.cs, src/PluginNodes/UserDefinedPluginNodes.cs
* Add custom namespace for plugin nodes
* Add boiler namespace and node to dumped pn.json
=> Add namespace to plugin nodes

src/AlarmCondition/AlarmConditionNodeManager.cs, src/AlarmCondition/Model/SourceState.cs, src/DeterministicAlarms/DeterministicAlarmsNodeManager.cs, src/SimpleEvent/SimpleEventsNodeManager.cs, tests/DeterministicAlarmsTests.cs, tests/MonitoringTestsBase.cs
* Convert severity for FluentAssertions 6.1.0 to work properly as it handles Enums [differently/better](https://fluentassertions.com/upgradingtov6#enums)
* Some cosmetic improvements
=> Convert severity from ushort to EventSeverity enum

src/PlcServer.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj
Nuget Update
```
[ ] Yes
[x] No
```
=> Update OPC SDK nuget packages

opcplc.sln, src/DeterministicAlarms/Configuration/Configuration.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj, tools/scripts/acr-build.ps1, tools/scripts/docker-build.ps1, tools/scripts/docker-source.ps1, tools/scripts/get-matrix.ps1, tools/scripts/get-version.ps1, tools/templates/acrbuild.yml, tools/templates/ci.yml, version.json
* Update sln to VS2022
* Update projects to .NET 6
* Update docker runtime to .NET 6
* Update nuget packages
=> Update to .NET 6.0

README.md, src/CliOptions.cs, src/Helpers/PnJsonHelper.cs, src/Program.cs
* Improve output of usage help
* Add to readme
* Remove InitAppLocation
=> Add command-line reference to readme

.github/dependabot.yml, .github/workflows/codeql-analysis.yml
=> Add CodeQL scanner

src/AlarmCondition/QuickstartNodeManager.cs, src/OpcApplicationConfigurationSecurity.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj
* Update packages
* Fix breaking changes
=> Update nuget packages

src/PluginNodes/SlowFastCommon.cs
Currently, fast and slow bad nodes can't be disabled.  The capability to do this.
* ...
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> Allow ability to turn on/off the fast and slow bad nodes

version.json
Bumped version from `2.2.0` to `2.3.0` as the latest release is [`2.3.0`](https://github.com/Azure-Samples/iot-edge-opc-plc/releases/tag/2.3.0).
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other: Aligning release version with version of container and version reported in logs.
```
=> Bumped version from 2.2.0 to 2.3.0.

README.md, src/PlcNodeManager.cs, src/PluginNodes/DeterministicGuidPluginNodes.cs, src/PluginNodes/SpecialCharNamePluginNode.cs
add a couple nodes having opaque respectively guid types
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
=> add an opaque and a guid nodes to special nodes folder

src/opc-plc.csproj, tests/opc-plc-tests.csproj, tools/scripts/acr-build.ps1, tools/scripts/build.ps1, tools/scripts/docker-source.ps1, version.json
=> Fix build platforms and update nuget

src/PlcNodeManager.cs, src/PluginNodes/UserDefinedPluginNodes.cs, version.json
* SDK call started to reject numeric node ID deserialized as longm when it should have been uint
=> Fix nodesjson issue with numeric node ID

README.md, tools/scripts/acr-build.ps1, version.json
=> Rename master to main

README.md, src/CliOptions.cs, src/OpcApplicationConfiguration.cs, src/OpcApplicationConfigurationSecurity.cs, src/Program.cs, version.json
* Adds additional DNS names and IP addresses to the server cert
=> Add option cdn for cert DNS names

src/OpcApplicationConfiguration.cs
* Activate OPC UA Stack server feature `Audit Events`  to observe the security events from OPC UA client
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
* Start the OPC PLC
* Start `UA Expert` and connect to OPC PLC
* Open Events View document
* Drag and Drop Server object into Configuration
* Active `AuditEventType`
```
Observe Events
```
* n/a
=> Activate `Audit Events` to observe security actions

src/AlarmCondition/Model/SourceState.cs, src/AlarmCondition/QuickstartNodeManager.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystem.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystemSource.cs, src/DeterministicAlarms/DeterministicAlarmsNodeManager.cs, src/OpcApplicationConfigurationSecurity.cs, src/PlcNodeManager.cs, src/Program.cs, src/SimpleEvent/SimpleEventsNodeManager.cs, tests/opc-plc-tests.csproj
* Log OutOfMemoryException and close app when encountering it (e.g. when running in a pod with very limited resources)
* Update some nuges
* Cosmetic and consistency improvements
=> Deal with OutOfMemoryException in alarms

README.md, src/CliOptions.cs, src/OpcApplicationConfiguration.cs, tests/opc-plc-tests.csproj, version.json
fix start failure when running in k8s context due to own certificate generated with different pod hostname
when running in k8s context and pki is set to a volume mount, the server fails to restart after pod's deletion, because the alternate domain names contain the pod's hostname name which is changed by k8s with every pod delete.
Logs: 
```
[21:52:37 INF] Check application instance certificate. [CN=OpcPlc] [619B3829CE368A8F0946C791DA23532C1ADD1092]
[21:52:37 INF] Check domains in certificate.
[21:52:37 INF] Server Domain names:
[21:52:37 INF]  opcplc.e4i-runtime
[21:52:37 INF]  opcplc
[21:52:37 INF]  opcplc-747d795f5-57d2b
[21:52:37 INF] Certificate Domain names:
[21:52:37 INF]  OPCPLC.E4I-RUNTIME
[21:52:37 INF]  OPCPLC
[21:52:37 INF]  OPCPLC-747D795F5-8B5FV
[21:52:37 ERR] The server is …
```
=> fix start failure when running in k8s context 

src/SimpleEvent/SimpleEventsNodeManager.cs, version.json
* Fix crash with event translation
=> Simplify event message

README.md, src/PlcNodeManager.cs, src/PluginNodes/NodeSet2PluginNodes.cs, src/PluginNodes/UaNodesPluginNodes.cs, src/PluginNodes/UserDefinedPluginNodes.cs, src/opc-plc.csproj, version.json
* Load NodeSet2.xml files
* Update nugets
* Update readme
=> Add feature to load NodeSet2.xml files

src/Helpers/CliHelper.cs, src/Helpers/PluginNodesHelper.cs, src/Helpers/PnJsonHelper.cs, src/PlcSimulation.cs, src/PluginNodes/ADeviceInformationPluginNodes.cs, src/PluginNodes/Boiler2PluginNodes.cs, src/PluginNodes/ComplexTypeBoilerPluginNode.cs, src/PluginNodes/FastPluginNodes.cs, src/PluginNodes/SlowFastCommon.cs, src/PluginNodes/SlowPluginNodes.cs
* Add CLI options to configure Boiler #2
* Add temperature simulation
=> Add Boiler #2 CLI options and simulation

src/PluginNodes/Boiler2PluginNodes.cs
* Add auto-on/off
* Update TODOs
=> Extend boiler 2 simulation

src/PluginNodes/Boiler2PluginNodes.cs
* start adding deviceHealth and events
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> start adding deviceHealth and events

src/ModelCompilerNodeSet2.cmd, src/PlcNodeManager.cs, src/PlcSimulation.cs, src/PluginNodes/ADeviceInformationPluginNodes.cs, src/PluginNodes/Boiler2PluginNodes.cs, src/PluginNodes/ComplexTypeBoilerPluginNode.cs, src/PluginNodes/DataPluginNodes.cs, src/PluginNodes/DipPluginNode.cs, src/PluginNodes/LongIdPluginNode.cs, src/PluginNodes/LongStringPluginNodes.cs, src/PluginNodes/NegTrendPluginNode.cs, src/PluginNodes/OpaquePluginNode.cs, src/PluginNodes/PosTrendPluginNode.cs, src/PluginNodes/SpecialCharNamePluginNode.cs, src/PluginNodes/SpikePluginNode.cs, src/PluginNodes/UaNodesPluginNodes.cs, src/PluginNodes/UserDefinedPluginNodes.cs, src/Program.cs, src/SimpleEvent/ModelDesign.xml, src/SimulatedVariableNode.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj
* Small improvements and refactorings
* Update nugets
=> Small improvements

src/PluginNodes/Boiler2PluginNodes.cs, tests/Boiler2Tests.cs, tests/BoilerTests.cs, tests/DataMonitoringTests.cs, tests/DataRandomizationTests.cs, tests/EventInstancesTests.cs, tests/SimulatorNodesTests.cs
* Add tests for configuration setting and simulation rise/fall
=> Add unit tests for boiler 2

src/PluginNodes/Boiler2PluginNodes.cs
* add device health events
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> Add device health events

src/PluginNodes/Boiler2PluginNodes.cs, tests/Boiler2Tests.cs, version.json
* Simulation step fixed so that even if base temp is off_spec, it can never be bigger than the temp speed
* Add test for off_spec 1
=> Fix boiler 2 simulation step

src/PluginNodes/Boiler2PluginNodes.cs, tests/Boiler2DeviceHealthEventsTests.cs, tests/Boiler2Tests.cs, tests/opc-plc-tests.csproj, version.json
* Use more meaningful event messages
=> Update boiler 2 event messages

README.md, src/PluginNodes/Boiler2PluginNodes.cs, version.json
* Fix range and update spec in readme
=> Fix range for failure

README.md, src/CliOptions.cs, src/OpcApplicationConfiguration.cs, version.json
add CLI options to control the:
* maximum session count
* maximum subscription count
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add configuration for maximum sessions & subscriptions

README.md, src/CliOptions.cs, src/OpcApplicationConfiguration.cs, version.json
Added CLI option to control:
- maximum queued request count
Similar to #274.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
=> add configuration for maximum queued request count

src/CliOptions.cs, src/PlcServer.cs, src/Program.cs, version.json
* Show build and SDK version on startup (loglevel debug)
* Show build and SDK version under Server -> ServerStatus -> BuildInfo
=> Show build and SDK version

src/PluginNodes/Boiler2PluginNodes.cs, tests/Boiler2DeviceHealthEventsTests.cs, version.json
* Use SourceName from CurrentTemperature node instead, which is the SourceNode
=> Remove set SourceName for temp events

src/AlarmCondition/AlarmConditionNodeManager.cs, src/AlarmCondition/Model/SourceState.cs, src/AlarmCondition/QuickstartNodeManager.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystemAlarmStates.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystemSource.cs, src/DeterministicAlarms/Model/SimConditionStatesEnum.cs, src/PluginNodes/UserDefinedPluginNodes.cs, src/nodesfile.json, tests/FastTimerTests.cs, tests/MonitoringTestsBase.cs, tests/PlcSimulatorFixture.cs, tests/SimulatorTestsBase.cs, version.json
* Fix regression caused by [Better NodeId/ExpandedNodeId built in types handling](https://github.com/OPCFoundation/UA-.NETStandard/pull/2230)
* Small SQ and cosmetic improvements
=> Fix nodeId regression

src/DeterministicAlarms/Configuration/ScriptException.cs, src/DeterministicAlarms/DeterministicAlarmsNodeManager.cs, src/DeterministicAlarms/Model/SimSourceNodeState.cs, src/DeterministicAlarms/ScriptEngine.cs, src/Program.cs, tests/DataRandomizationTests.cs, tests/GuidNodesTests.cs, tests/PlcSimulatorFixture.cs, tests/SimulatorTestsBase.cs, tests/UserDefinedNodesTests.cs
* Add tests for nodesfile.json
* Fix test for deterministic GUID
* Cosmetic and style improvements
=> Add tests for nodesfile.json

src/Extensions/CancellationTokenExtensions.cs, src/Program.cs
* Use this [extension](https://github.com/dotnet/runtime/issues/14991#issuecomment-131221355)
=> Await cancellationtoken

src/OpcApplicationConfiguration.cs, src/PlcServer.cs, src/opc-plc.csproj, version.json
* Improve default server settings
* Cosmetic improvements
=> Update server settings

.github/workflows/codeql-analysis.yml, src/PluginNodes/Boiler2PluginNodes.cs, src/opc-plc.csproj, tests/PlcSimulatorFixture.cs, tests/opc-plc-tests.csproj, tools/templates/acrbuild.yml, tools/templates/ci.yml, version.json
* Update .NET
* Fix breaking issues
=> Update to .NET 8

tools/scripts/docker-source.ps1
Doc: https://hub.docker.com/_/microsoft-dotnet-runtime-deps/
=> Update dotnet runtime to 8.0-bookworm-slim

.editorconfig, src/OpcApplicationConfiguration.cs, tests/DataMonitoringTests.cs, tests/DeterministicAlarmsTests2.cs, tests/PlcSimulatorFixture.cs, tests/SimulatorNodesTests.cs, tests/SimulatorTestsBase.cs, tests/opc-plc-tests.csproj, tools/scripts/acr-build.ps1, tools/scripts/docker-source.ps1, version.json
* Add [--self-contained](https://learn.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) to build step to be able to use [microsoft-dotnet-runtime-deps](https://hub.docker.com/_/microsoft-dotnet-runtime-deps/)
* Fix some issues found by analyzers
* Upgrade NUnit and fix breaking changes
=> Fix .NET 8 breaking change

README.md, src/CliOptions.cs
* Fix loglevel options
* Update readme
* Fixes issue introduced by #314 
* Fixes #321
=> Fix loglevel options

samples/OpcPlcBase.cs, src/AlarmCondition/AlarmConditionNodeManager.cs, src/PlcServer.cs, src/Program.cs, src/opc-plc.csproj, tests/PlcSimulatorFixture.cs, tests/opc-plc-tests.csproj
* Allow use of opc ua preview nuget
* Throw exception when failing to start server to give feedback to the nuget start
=> Allow use of opc ua preview nugets

src/FlatDirectoryCertificateStore.cs, src/FlatDirectoryCertificateStoreType.cs, src/OpcApplicationConfiguration.cs, src/OpcApplicationConfigurationSecurity.cs
* add prefix for the FlatDirectory certificates store type so that multiple certificate store types can coexist in the same process
```
[ ] Yes
[x] No
```
```
[x] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...
=> add prefix for the FlatDirectory certificates store type

README.md, src/CliOptions.cs, src/Configuration.cs, src/Helpers/DeterministicGuid.cs, src/PluginNodes/DeterministicGuidPluginNodes.cs, src/Program.cs, tests/GuidNodesTests.cs, version.json
* Add RestartAsync to restart PLC and simulation
* Refactor for improve config reset
* Make deterministic GUID helper an instance class for reusability
* Re-enable deterministic GUID tests
=> Add RestartAsync

README.md, src/CliOptions.cs, src/PluginNodes/FastPluginNodes.cs, src/PluginNodes/SlowFastCommon.cs, src/PluginNodes/VeryFast1KBPluginNodes.cs, src/TimeService.cs
=> Add very fast 1 kB nodes

src/Configuration/OpcUaAppConfigFactory.cs, src/Logging/LoggingProvider.cs, src/PluginNodes/SlowFastCommon.cs, tests/opc-plc-tests.csproj, version.json
* Decrease ChannelLifetime to 60 s to avoid sockets dangling for 10 min
=> Decrease ChannelLifetime to 60 s

src/BaseDataVariableStateExtended.cs, src/PluginNodes/SpecialCharNamePluginNode.cs, version.json
=> Fix fast/slow node types bool and uintarray

src/opc-plc.csproj, tests/opc-plc-tests.csproj
=> Use opc sdk 1.5.374.33-preview

README.md, src/Configuration/CliOptions.cs, src/Configuration/OpcApplicationConfiguration.cs, src/Configuration/OpcUaAppConfigFactory.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj, version.json
* Add MaxSessionTimeout
* Update nugets
Fixes #359
=> Add MaxSessionTimeout

README.md, src/PluginNodes/VeryFast1KBPluginNodes.cs, src/PluginNodes/VeryFastByteStringPluginNodes.cs, version.json
* Similar to 1 kB nodes, but the size can be configured
=> Add very fast ByteString nodes

src/AlarmCondition/AlarmConditionNodeManager.cs, src/PlcServer.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj, version.json
* Gracefully handle publish BadNoSubscription error
* Update nugets incl. OPC UA SDK 1.5.374.78
* Periodically log open sessions and subscriptions every 60 s
=> Improve publish BadNoSubscription

src/PlcServer.cs, version.json
* Gracefully handle two additional common publish errors
=> Improve publish BadSessionIdInvalid and BadSecureChannelIdInvalid

README.md, src/Configuration/OpcUaAppConfigFactory.cs, src/PlcServer.cs, tests/opc-plc-tests.csproj
=> Update readme and test nuget

README.md
Enhance the `json` code block format for README.md that will read easier with highlighted syntax.
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
=> Enhance the `json` code block format for README.md that will read easier with highlighted syntax.

src/Configuration/OpcUaAppConfigFactory.cs, src/FlatDirectoryCertificateStore.cs, src/opc-plc.csproj, tests/opc-plc-tests.csproj, version.json
* Update SDK
* Fix breaking changes
=> Use OPC UA SDK 1.5.374.118

src/opc-plc.csproj, tests/opc-plc-tests.csproj, version.json
Use Nuget package which fixes token renewal issue
see https://github.com/OPCFoundation/UA-.NETStandard/releases/tag/1.5.374.176
=> Bump to Nuget with fix for token renewal

README.md, src/Configuration/CliOptions.cs, src/Configuration/Configuration.cs, src/PlcServer.cs
Port chaos mode from OPC Publisher test server
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
=> Port chaos mode from OPC Publisher test server

src/PlcServer.cs, src/opc-plc.csproj, version.json
* Log only items that actually support a subscription and were subscribed to successfully
* Update 1 nuget
=> Improve subscribed log

src/AlarmCondition/AlarmConditionNodeManager.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystem.cs, src/AlarmCondition/UnderlyingSystem/UnderlyingSystemSource.cs, version.json
* Cycle through WestTank, EastTank, NorthMotor and SouthMotor every 1/s
=> Add deterministic events
