README.md
src/PlcNodeManager.cs
tools/templates/azuredeploy.opcplc.aci.json

* Tested with up to 2 mio slow + 2 mio fast nodes in westeurope (4 CPUs, 16 GB RAM)

Add AZ deploy button and ARM template

---

README.md
src/PlcNodeManager.cs
tests/PlcSimulatorFixture.cs
tests/SimulatorNodesTests.cs
tests/SimulatorTestsBase.cs

* Added methods to control the Fast and Slow nodes to allow control in test environment
```
[ ] Yes
[X ] No
```
```
[ ] Bugfix
[ X] Feature
```
*  execute test SimulatorNodesTests.Telemetry_FastNode() in visual studio test runner
* n/a
* n/a

Add OPC UA methods to stop and start updating value of fast and slow nodes

---

src/OpcApplicationConfiguration.cs
version.json

* The UA-.NET standard client creates at least on publishing request per subscription created. The OPC PLC set max subscription to 200 but the max publishing request is using the stack default of 20.
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
* Build OPC PLC from source
* Start OPC PLC 
* Connect UA-.NET OPC UA Client and create more than 20 Subscriptions
* Observe that no exception of type `BadTooManyPublishingRequests` is thrown
* More then subscription could be created

Set MaxPublishingRequestCount to same MaxSubscriptionCount

---

README.md
src/Helpers/DeterministicGuid.cs
src/NamespaceType.cs
src/Nodes/DeterministicGuidNodes.cs
src/Nodes/INodes.cs
src/PlcNodeManager.cs
src/PlcSimulation.cs
src/Program.cs
src/TimeService.cs
tests/DataMonitoringTests.cs
tests/GuidNodesTests.cs
version.json

* Add deterministic GUID nodes
* Makes it easier to test transport that uses compression by using GUIDs that cannot be compressed efficiently
* Add functionality as encapsulated class that implements INodes, this will make it easier to add new encapsulated functionality in the future
* Further refactoring can be done to automatically load all implementations of INodes

Add deterministic GUID nodes

---

src/CliOptions.cs
src/OpcApplicationConfiguration.cs
src/OpcApplicationConfigurationSecurity.cs
src/Program.cs
src/opc-plc.csproj
tests/opc-plc-tests.csproj
version.json

* Add alternate base address set to the internal DNS names. This should fix the connection issue when the internal container name doesn't match the external name used in the certificate (e.g. option `--ph`).
* Update some nuget packages
* Use semantic logging for many logs

Add alternate base address

---

src/Helpers/PluginNodesHelpers.cs
src/Helpers/PnJsonHelper.cs
src/PluginNodes/ComplexTypeBoilerPluginNode.cs
src/PluginNodes/DeterministicGuidPluginNodes.cs
src/PluginNodes/DipPluginNode.cs
src/PluginNodes/LongIdPluginNode.cs
src/PluginNodes/LongStringPluginNodes.cs
src/PluginNodes/Models/NodeWithIntervals.cs
src/PluginNodes/NegTrendPluginNode.cs
src/PluginNodes/OpaquePluginNode.cs
src/PluginNodes/PosTrendPluginNode.cs
src/PluginNodes/SpecialCharNamePluginNode.cs
src/PluginNodes/SpikePluginNode.cs
src/PluginNodes/UserDefinedPluginNodes.cs
src/opc-plc.csproj
tests/opc-plc-tests.csproj
version.json

Fix generated pn.json for:
* Boiler
* Deterministic GUIDs
* Opaque node
* Set UseSecurity in pn.json to true if not using `--unsecuretransport`, otherwise to false
* Update nuget packages
Example:
```
pn.json
[
{
"EndpointUrl": "opc.tcp://********:50000",
"UseSecurity": false,
"OpcNodes": [
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/Boiler;i=15013" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=StepUp" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=AlternatingBoolean" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=RandomSignedInt32" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;s=RandomUnsignedInt32" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;g=51b74e55-f2e3-4a4d-b79c-bf57c76ea67c" },
{ "Id": "nsu=http://microsoft.com/Opc/OpcPlc/;g=1313895e-c776-4201-b893-e514864c669 …
```

Fix pn.json generation

---

README.md
src/CliOptions.cs
src/PlcSimulation.cs
src/PluginNodes/ComplexTypeBoilerPluginNode.cs
src/PluginNodes/LongIdPluginNode.cs
src/PluginNodes/LongStringPluginNodes.cs
src/PluginNodes/OpaquePluginNode.cs
src/PluginNodes/SpecialCharNamePluginNode.cs
src/PluginNodes/UserDefinedPluginNodes.cs
src/Program.cs
tests/DeterministicAlarmsTests.cs
tests/DeterministicAlarmsTests2.cs
tests/MonitoringTestsBase.cs
tests/PlcSimulatorFixture.Config.xml
tests/PlcSimulatorFixture.cs
tests/SimulatorTestsBase.cs
version.json

* Enable some features by default: complextypeboiler (--ctb), longid (--lid), longstringnodes (--lsn), opaquenode (--on), specialcharname (--scn), referencetest
* Remove default features from command line arguments list
* When invalid args specified, warn instead of fail

Enable some features by default

---

README.md
src/CliOptions.cs
src/OpcApplicationConfigurationSecurity.cs
src/PluginNodes/UaNodesPluginNodes.cs
src/Program.cs
version.json

* Add option `DontRejectUnknownRevocationStatus` to disable `RejectUnknownRevocationStatus`, which is enabled by default
* When `DontRejectUnknownRevocationStatus` is set to `true`, it will NOT reject chain validation with CA certs with unknown revocation status, e.g. when the CRL is not available or the OCSP provider is offline
Fixes #202

Add DontRejectUnknownRevocationStatus

---

README.md

Folder /appdata does not exist in the container image. it's `/app` and the cert folder is `pki`.
* the default container app folder in docker file is `/app`, not `/appdata` , moreover the default main pki folder is `pki`
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Documentation content changes
```
* run the container image with the `-v` podman/docker option for pki persistency and observe that server certificate is located in /app/pki
The default WORKDIR here: <https://github.com/Azure-Samples/iot-edge-opc-plc/blob/main/tools/scripts/docker-source.ps1#L172> is `/app`

update path for certificate persistency

---

README.md
src/ConfigNode.cs
src/PlcNodeManager.cs
src/PluginNodes/UserDefinedPluginNodes.cs
src/nodesfile.json

Adds nested folder structure support to user node configuration
Adds guid node id support to user node configuration
* Users can create a nested node structures for testing purposes.
* Users can create nodes with a guid node id type for testing purposes.
```
[ ] Yes
[x] No
```
Might break for users that have an existing user node configuration with a guid node id but expect it to be of node id type string.
```
[ ] Bugfix
[x] Feature
```
*  Get the code and run with `--nf nodesfile.json`
* Verify that `MyTelemetry` folder has a …

Adds nested folder structure and guid node id support to user node configuration

---

src/PluginNodes/Boiler2PluginNodes.cs
tests/Boiler2DeviceHealthEventsTests.cs
version.json

* Set current temp node as source for temp-related events
* Keep null as source for maintenance event
[Spec](https://reference.opcfoundation.org/Core/Part5/v104/docs/6.4.2): If the Event is not specific to a Node the NodeId is set to null.

Specify event source

---

src/opc-plc.csproj
tests/opc-plc-tests.csproj
version.json

Contains commits from those PRs:
- #290 
- #292 
- #293 
- #294 
- #295
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```

upgrade NuGet packages

---

README.md
src/CliOptions.cs
src/FlatDirectoryCertificateStore.cs
src/FlatDirectoryCertificateStoreType.cs
src/OpcApplicationConfiguration.cs
src/OpcApplicationConfigurationSecurity.cs
version.json

* add support for flat directory certificate store for k8s cert manager compatibility
* handle .crt and .key certificate types
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[x] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

enable flat directory certificate store for k8s cert-manager compatibility

---

src/opc-plc.csproj
tests/opc-plc-tests.csproj
version.json

* Fixes component governance warnings:
* [CVE-2024-32028](https://msazure.visualstudio.com/One/_componentGovernance/opcuabroker/alert/11099358?typeId=21797268) for `OpenTelemetry.Instrumentation.AspNetCore` (`1.8.0`).
* [CVE-2024-32028](https://msazure.visualstudio.com/One/_componentGovernance/opcuabroker/alert/11099357?typeId=21797268) for `OpenTelemetry.Instrumentation.Http` (`1.8.0`).
* Update OPC UA SDK to 1.5.374.36
```
[ ] Yes
[x] No
```
```
[ ] Bugfix
[ ] Feature
[x] Vulnerability fix
```

Upgrade nuget incl. OTEL

---

src/AlarmCondition/QuickstartNodeManager.cs
src/Configuration/OpcUaAppConfigFactory.cs
version.json

* Work around regression in 1.5.374.50-preview defaulting to MaxChannelCount 100
* Fix #357, which happened, for example, by creating a client subscription to Server -> Green -> East -> Blue -> SouthMotor -> OnlineState

Fix MaxChannelCount and alarm subscription

---

src/Reference/ReferenceNodeManager.cs

* Have deterministic DataValues after each restart of OPC PLC
* Apply latest changes from OPC UA ReferenceNodeManager
```
[ ] Yes
[X] No
```
```
[X] Bugfix
[ ] Feature
```
```
start the OPC PLC
Check the DataValue of `s=Scalar_Dynamic_NodeId`
restart the OPC PLC
Check the DataValue of `s=Scalar_Dynamic_NodeId` again
```
```
```
* ...

Set seed to fix value, to have deterministic datavalues

---

src/PlcServer.cs
src/PluginNodes/ComplexTypeBoilerPluginNode.cs
tests/BoilerTests.cs
tests/DeterministicAlarmsTests.cs
tests/DeterministicAlarmsTests2.cs

When used via NuGet package in-memory, the server needs to use its own encodable factory. Otherwise, the client will not load the type definitions for decoding correctly. There is currently no public API to set the encodable factory and it is not possible to provide own implementation, because other classes require the `StandardServer` or `ServerInternalData` as objects, so we need to use reflection to set it. 
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[X] Feature
```
```
cd [repo-name]
npm install
```
* …

Do not add custom types into global EncodeableFactory

---

src/AlarmCondition/AlarmConditionNodeManager.cs
src/AlarmCondition/Model/SourceState.cs

`EventId`s are currently generate for each OPC PLC restart and each event, which makes testing against it, much harder. Thios change follows the pattern of the ReferenceNodeManager and generate deterministic IDs.
```
[ ] Yes
[X] No
```
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```
```
git clone this repository
start the OPC PLC with `--autoaccept --alm`
```
* navigate to
* After multiple restarts the initial EventId of the Node is the same

Enforce that initial `EventId`s are deterministic

---

src/Helpers/MetricsHelper.cs
src/Helpers/OtelHelper.cs
src/PlcServer.cs
tests/MetricsTests.cs
version.json

Remove redundant dimensions that were added to metrics causing memory issues for OTEL collector
Rename metrics class to be consistent as other helper classes.
Refactor and cleanup
```
[ ] Yes
[x] No
```
```
[] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Reduce Emulated PLC metrics

---

src/OpcPlcServer.cs
src/PlcServer.cs
version.json

* Periodically log thread info
* Improve error handling for creating monitored items, read and publish

Log threads

---

src/Helpers/MetricsHelper.cs
src/PlcServer.cs
tests/MetricsTests.cs
version.json

* Use code gen logging
* Move metric calculation to helper to avoid execution when disabled
* Disable publish metrics when connected to more than 40 sessions or monitoring more than 500 items for better perf

Use code gen logging

---

README.md
src/AlarmCondition/AlarmConditionNodeManager.cs
src/PlcNodeManager.cs
src/PlcServer.cs
src/PluginNodes/VeryFast1KBPluginNodes.cs
src/PluginNodes/VeryFastByteStringPluginNodes.cs
src/PluginNodes/WorkingSetPluginNode.cs
version.json

* Use single array as content for all VeryFastByteString nodes to save memory
* Add total sessions/subscriptions to periodic log
* Use loglevel check for more efficient logging in hot paths
* Add node with WorkingSetMB

Use single array as content for all VeryFastByteString nodes to save memory

---

Directory.Build.targets
opcplc.sln
src/PlcServer.cs
src/opc-plc.csproj

* Improve SDk debugging
* Handle BadSessionClosed

Add boilerplate to reference local OPC UA SDK

---

src/nuget.config
src/opc-plc.csproj
tests/nuget.config
tests/opc-plc-tests.csproj

* Includes [Fix a deadlock in binary channel on cleanup, reduce contention due to locks on high server load #2714](https://github.com/OPCFoundation/UA-.NETStandard/pull/2714)

Use OPC UA SDK 1.5.374-preview.g1a7d9b8e51

---

scripts/run
snap/hooks/configure
snap/hooks/default-configure
snap/snapcraft.yaml
src/CompanionSpecs/DI/DiNodeManager.cs
src/OpcPlcServer.cs
src/PluginNodes/Boiler2PluginNodes.cs
src/PluginNodes/ComplexTypeBoilerPluginNode.cs
src/SimpleEvent/SimpleEventsNodeManager.cs

Changes to be able to build and run the server as a snap.
This is a minimal snap containing:
- some hard-coded cli options on the run command
- one snap configuration exposed _trustedcertbase64_, for configuring a trusted certificate
This minimal snap version should be enough to run the [Azure IoT Operations Quickstart](https://learn.microsoft.com/en-us/azure/iot-operations/get-started-end-to-end-sample/quickstart-deploy) with a plc simulator that is outside of the Kubernetes cluster and able to securely communicate with the cluster.

Snap with dotnet plugin

---

snap/snapcraft.yaml

Add explicit build architectures on snapcraft.yaml (amd64, arm64). Otherwise Launchpad tries to build the snap for more (all) architectures and fails.

chore: Add snap build architectures

---

src/opc-plc.csproj
tests/opc-plc-tests.csproj

* Use exact OPC UA SDK version to avoid conflicting with another version being pulled by a project that references the OPC PLC via Nuget
Reference: https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges

Use exact SDK version

---

src/PluginNodes/UserDefinedPluginNodes.cs
src/nodesfile.json

* Add support for Int32, UInt32, String, Float and Boolean array values in nodesfile.json

Fix nodesfile.json array values

---

src/PluginNodes/UserDefinedPluginNodes.cs
version.json

Unsafe TypeNameHandling
[
BUG 30480450: [S360] Address CodeQL finding: "Unsafe TypeNameHandling' in src/PluginNodes/UserDefinedPluginNodes.cs](https://msazure.visualstudio.com/One/_workitems/edit/30480450)
```
[ ] Yes
[ x] No
```
```
[ ] Bugfix
[ ] Feature
```
```
cd [repo-name]
npm install
```
```
```
* ...

Fix Unsafe TypeNameHandling
